// Generic blackbox handling (SPEC §11.4). Nothing here knows any module name:
// missing modules come from the front-end's diagnostics, port names from the
// instantiation sites, widths/directions from the elaborated connections and
// the connection expression text.

import fs from 'node:fs';

export function stripComments(text) {
  let out = '';
  let i = 0;
  while (i < text.length) {
    const c = text[i];
    const n = text[i + 1];
    if (c === '"') {
      const end = findStringEnd(text, i);
      out += text.slice(i, end);
      i = end;
    } else if (c === '/' && n === '/') {
      while (i < text.length && text[i] !== '\n') i += 1;
    } else if (c === '/' && n === '*') {
      const end = text.indexOf('*/', i + 2);
      const stop = end < 0 ? text.length : end + 2;
      out += text.slice(i, stop).replace(/[^\n]/g, ' ');
      i = stop;
    } else {
      out += c;
      i += 1;
    }
  }
  return out;
}

function findStringEnd(text, start) {
  let i = start + 1;
  while (i < text.length && text[i] !== '"') i += text[i] === '\\' ? 2 : 1;
  return Math.min(text.length, i + 1);
}

function balancedEnd(text, openIndex, open = '(', close = ')') {
  let depth = 0;
  for (let i = openIndex; i < text.length; i += 1) {
    if (text[i] === open) depth += 1;
    else if (text[i] === close) {
      depth -= 1;
      if (depth === 0) return i;
    }
  }
  return -1;
}

function lineOf(text, index) {
  let line = 1;
  for (let i = 0; i < index; i += 1) if (text.charCodeAt(i) === 10) line += 1;
  return line;
}

function splitTopLevel(body, separator = ',') {
  const parts = [];
  let depth = 0;
  let start = 0;
  for (let i = 0; i <= body.length; i += 1) {
    const ch = body[i];
    if (ch === '(' || ch === '{' || ch === '[') depth += 1;
    else if (ch === ')' || ch === '}' || ch === ']') depth -= 1;
    if ((ch === separator && depth === 0) || i === body.length) {
      parts.push(body.slice(start, i));
      start = i + 1;
    }
  }
  return parts;
}

// Find `<module> [#(...)] <inst> ( ... );` for the given module names and
// return named port connections. Positional connections are reported so the
// caller can emit rtl/blackbox-port-unknown.
export function scanInstantiations(fileTexts, moduleNames) {
  const wanted = new Set(moduleNames);
  const sites = [];
  for (const { file, text: raw } of fileTexts) {
    const text = stripComments(raw);
    const re = /\b([A-Za-z_]\w*)\s*(#\s*\()?/g;
    let match;
    while ((match = re.exec(text))) {
      const moduleName = match[1];
      if (!wanted.has(moduleName)) continue;
      let cursor = match.index + match[0].length;
      if (match[2]) {
        const end = balancedEnd(text, cursor - 1);
        if (end < 0) continue;
        cursor = end + 1;
      }
      const inst = /^\s*([A-Za-z_]\w*)\s*(\[[^\]]*\]\s*)?\(/.exec(text.slice(cursor));
      if (!inst) continue;
      const open = cursor + inst[0].length - 1;
      const close = balancedEnd(text, open);
      if (close < 0) continue;
      const ports = [];
      let positional = false;
      for (const segment of splitTopLevel(text.slice(open + 1, close))) {
        const s = segment.trim();
        if (!s) continue;
        const named = /^\.([A-Za-z_]\w*)\s*(?:\(([\s\S]*)\))?$/.exec(s);
        if (named) ports.push({ name: named[1], expr: named[2]?.trim() ?? null });
        else positional = true;
      }
      sites.push({ module: moduleName, instance: inst[1], file, line: lineOf(text, match.index), ports, positional });
      re.lastIndex = close;
    }
  }
  return sites;
}

export function parseMissingModules(toolOutput) {
  // Verilator: "%Error-MODMISSING: file:line:col: Cannot find file containing module: 'name'"
  const names = new Set();
  for (const m of toolOutput.matchAll(/Cannot find file containing module: '([^']+)'/g)) names.add(m[1]);
  return [...names].sort();
}

// Pass-1 stub: port names only, generous width, all inputs. Directions and
// widths are refined from the elaborated connections in pass 2.
export const PLACEHOLDER_WIDTH = 1024;

export function placeholderStubs(sites) {
  const byModule = new Map();
  for (const site of sites) {
    const ports = byModule.get(site.module) || new Set();
    for (const p of site.ports) ports.add(p.name);
    byModule.set(site.module, ports);
  }
  return [...byModule.entries()].sort(([a], [b]) => a.localeCompare(b)).map(([module, ports]) => ({
    module,
    ports: [...ports].map((name) => ({ name, dir: 'in', width: PLACEHOLDER_WIDTH })),
  }));
}

export function stubSource(stubs, { origin }) {
  const lines = [`// Generated by rtl-figures (${origin} blackbox stubs). Do not edit; regenerate instead.`];
  for (const stub of stubs) {
    const decls = stub.ports.map((p) => {
      const dir = p.dir === 'out' ? 'output' : p.dir === 'inout' ? 'inout' : 'input';
      const range = p.width > 1 ? ` [${p.width - 1}:0]` : '';
      return `  ${dir} wire${range} ${p.name}`;
    });
    lines.push(`module ${stub.module} (`);
    lines.push(decls.join(',\n'));
    lines.push(');');
    lines.push('endmodule');
    lines.push('');
  }
  return lines.join('\n');
}

// Width of a connection expression from its source text, resolved against the
// parent module's nets and params. Returns null when it cannot be determined
// (unsized literals, function calls, operators whose width depends on context).
export function exprTextWidth(text, nets = []) {
  const byName = new Map(nets.map((n) => [n.name, n]));
  const valueOf = (t) => {
    const s = t.trim().replace(/^\((.*)\)$/s, '$1').trim();
    if (/^\d+$/.test(s)) return Number(s);
    const sized = /^(\d+)?'[sS]?([bodhBODH])([0-9a-fA-F_]+)$/.exec(s);
    if (sized) return parseInt(sized[3].replace(/_/g, ''), { b: 2, o: 8, d: 10, h: 16 }[sized[2].toLowerCase()]);
    const net = byName.get(s);
    if (net?.kind === 'param' && net.value !== undefined && /^-?\d+$/.test(net.value)) return Number(net.value);
    return null;
  };
  const width = (t) => {
    let s = t.trim();
    while (s.startsWith('(') && balancedEnd(s, 0) === s.length - 1) s = s.slice(1, -1).trim();
    if (!s) return null;
    const sized = /^(\d+)'[sS]?[bodhBODH][0-9a-fA-F_xXzZ?]+$/.exec(s);
    if (sized) return Number(sized[1]);
    if (/^'[01xXzZ]$|^\d+$|^'[sS]?[bodhBODH]/.test(s)) return null;
    if (/^[~-]/.test(s)) return width(s.slice(1));
    if (s.startsWith('!')) return 1;
    if (s.startsWith('{') && balancedEnd(s, 0, '{', '}') === s.length - 1) {
      const inner = s.slice(1, -1).trim();
      const rep = /^([^{}]+?)\s*(\{[\s\S]*\})$/.exec(inner);
      if (rep && balancedEnd(rep[2], 0, '{', '}') === rep[2].length - 1) {
        const count = valueOf(rep[1]);
        const w = width(rep[2].slice(1, -1));
        return count !== null && w !== null ? count * w : null;
      }
      let total = 0;
      for (const part of splitTopLevel(inner)) {
        const w = width(part);
        if (w === null) return null;
        total += w;
      }
      return total;
    }
    const select = /^([A-Za-z_]\w*)\s*\[([^\]:]+)(?::([^\]]+))?\]$/.exec(s);
    if (select) {
      if (select[3] === undefined) return 1;
      const hi = valueOf(select[2]);
      const lo = valueOf(select[3]);
      return hi !== null && lo !== null ? Math.abs(hi - lo) + 1 : null;
    }
    if (/^[A-Za-z_]\w*$/.test(s)) return byName.get(s)?.width ?? null;
    return null;
  };
  return width(String(text));
}

// Pass-2 refinement from a netlist elaborated against placeholder stubs.
// `sites` (from scanInstantiations) supply expression text so literal and
// expression widths are not taken from the placeholder-resized tree.
export function refineStubs(netlist, stubModuleNames, sites = []) {
  const wanted = new Set(stubModuleNames);
  const byModule = new Map();
  const unresolved = [];
  for (const mod of netlist.modules) {
    const writers = new Set();
    for (const dep of mod.deps || []) writers.add(dep.target);
    for (const port of mod.ports) if (port.dir === 'in' || port.dir === 'inout') writers.add(port.name);
    const childOutputs = new Set();
    for (const inst of mod.instances) {
      if (wanted.has(inst.orig_module)) continue;
      for (const c of inst.connections) if (c.dir === 'out' && c.expr.net) childOutputs.add(c.expr.net);
    }
    for (const inst of mod.instances) {
      if (!wanted.has(inst.orig_module)) continue;
      const leaf = inst.name.split('.').pop();
      const site = sites.find((s) => s.module === inst.orig_module && s.instance === leaf);
      const ports = byModule.get(inst.orig_module) || new Map();
      for (const c of inst.connections) {
        const e = c.expr;
        if (e.kind === 'open') {
          unresolved.push({ module: inst.orig_module, instance: inst.name, port: c.port, reason: 'unconnected' });
          continue;
        }
        const dir = e.kind === 'net' || e.kind === 'slice'
          ? (writers.has(e.net) || childOutputs.has(e.net) ? 'in' : 'out')
          : 'in';
        const text = site?.ports.find((p) => p.name === c.port)?.expr;
        const textWidth = text ? exprTextWidth(text, mod.nets || []) : null;
        const treeWidth = e.width ?? c.width;
        const width = textWidth ?? (treeWidth && treeWidth !== PLACEHOLDER_WIDTH ? treeWidth : null);
        if (width === null) {
          unresolved.push({ module: inst.orig_module, instance: inst.name, port: c.port, reason: `width of '${text ?? e.kind}' not determinable` });
          continue;
        }
        const prev = ports.get(c.port);
        if (prev && (prev.width !== width || prev.dir !== dir)) {
          prev.conflict = true;
          prev.width = Math.max(prev.width, width);
          if (prev.dir !== dir) prev.dir = 'in';
        } else if (!prev) {
          ports.set(c.port, { name: c.port, dir, width, direction_inferred: true });
        }
      }
      byModule.set(inst.orig_module, ports);
    }
  }
  const stubs = [...byModule.entries()].sort(([a], [b]) => a.localeCompare(b)).map(([module, ports]) => ({ module, ports: [...ports.values()] }));
  return { stubs, unresolved };
}

export function readUserBlackboxes(jsonPaths) {
  const stubs = [];
  for (const p of jsonPaths) {
    const data = JSON.parse(fs.readFileSync(p, 'utf8'));
    for (const bb of Array.isArray(data) ? data : data.blackboxes || []) stubs.push(bb);
  }
  return stubs;
}
